### ISSUE TITLE
Twitch Point Message en avant c'est pété !

### ISSUE THREAD

**Issue by Nyrrell** [EvntBoard/module-twitch#1]
Bonjour !

Quand je veux catch un event Twitch MESSAGE EN AVANT, bah c'est pété :(

I don't speak english déso pas déso !

**Comment by evandikt** [comment]
@Nyrrell une props est maintenant dispo sur event.payload.msgId [commit](https://github.com/EvntBoard/module-twitch/commit/23d43a78c098f53151bf6d610b8dd96701e13a5d)
